### ISSUE TITLE
ERROR Could not find es.exe

### ISSUE THREAD

**Issue by Babbzzz** [reflog/cerebro-plugin-everything#1]
Hi,

I am receiving the following error when I use the plugin. 

`ERROR Could not find es.exe. Please check your settings`

**Comment by Babbzzz** [comment]
I use Everything Version 1.4.1.877 (x86)

**Comment by Babbzzz** [comment]
@reflog have you faced this issue before?

**Comment by reflog** [comment]
sorry, this plugin was never really finished. I doubt it'll work for you :)

**Comment by Babbzzz** [comment]
:(
